⬆️ UPGRADE: Autoupdate pre-commit config template (#101)
* ⬆️ UPGRADE: Autoupdate pre-commit config template

* ⬆️ UPGRADE: Autoupdate pre-commit config template

* ⬆️ UPGRADE: Autoupdate pre-commit config template

* 🩹 Fix mypy pre-commit env setup issue

All versions of the package `types-pkg-resources` (dependency of `types-all`) were yanked causing the following error when `pre-commit` tries to create the `mypy` venv.

```py
stderr:
    ERROR: Ignored the following yanked versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3
    ERROR: Could not find a version that satisfies the requirement types-pkg-resources (from types-all) (from versions: none)
    ERROR: No matching distribution found for types-pkg-resources
```
@s-weigand

* ⬆️ UPGRADE: Autoupdate pre-commit config template

---------

Co-authored-by: s-weigand <s-weigand@users.noreply.github.com>
Co-authored-by: s-weigand <s.weigand.phy@gmail.com>